name: Deploy to EC2

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          
      - name: Grant execute permission to gradlew
        run: chmod +x ./gradlew

      - name: Build Application
        run: |
          cd $GITHUB_WORKSPACE  # 워크플로우 실행 환경의 루트 디렉토리로 이동
          ./gradlew build
          ls -R
          
      - name: copy file via ssh key
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          port: 22
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "./build/libs/pro-0.0.1-SNAPSHOT.jar"
          target: ~/art_see_real/backend/server
          
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }} # EC2 인스턴스에 연결하기 위한 개인 키
          host: ${{ secrets.HOST }} # EC2 인스턴스 IP
          username: ${{ secrets.USER }} # EC2 인스턴스 사용자 이름
          script: |
            sudo /home/ubuntu/art_see_real/backend/server/art_see_real.sh
